import pyautogui
import time
time.sleep(3)
x=pyautogui.click(1003,1040)
print(x)
time.sleep(3)
y=pyautogui.click(1191,140)
print(y)
time.sleep(3)
z=pyautogui.click(1413,209)
print(z)
time.sleep(3)
h=pyautogui.write("Chatgpt")
print(h)
time.sleep(3)
g=pyautogui.hotkey("enter")
print(g)
time.sleep(3)
s=pyautogui.click(1026,787)
print(g)
time.sleep(3)
t=pyautogui.alert("Thank you guys for watching",3)
print(t)
time.sleep(3)
l=pyautogui.click(1706,11)
print(l)
